version: "3.8"

services:
  db:
    image: postgres:16
    container_name: juno_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: juno_time_dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5434:5432" # host:container
    volumes:
      - juno_pgdata:/var/lib/postgresql/data

volumes:
  juno_pgdata:
